# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Website for Alex Johnson
email: alexj777@gmail.com
description: > # this means to ignore newlines until "baseurl:"
          This site is currently a work in progress.
baseurl: "" # the subpath of your site, e.g. /blog
url: "alexanderwjohnson.com" # the base hostname & protocol for your site
twitter_username: alex_w_j
github_username:  awj4hd

# Build settings
markdown: kramdown
